-- SAMPLE SQL QUESTIONS

-- 1. List all hospitals with emergency services enabled.
SELECT * FROM HOSPITALS 
WHERE 
EMERGENCY_SERVICES = 1

-- 2. Count how many hospitals exist in each state.
SELECT STATE,
       COUNT(*) AS TOTAL_HOSPITALS
       FROM HOSPITALS 
       GROUP BY STATE
       
-- 3. Find the total number of patients admitted in each hospital.
SELECT HOSPITAL_ID,
       COUNT(*) AS NO_OF_PATIENTS
       FROM PATIENTS 
       GROUP BY 1
       
-- 4. Find hospitals with bed capacity greater than the average bed capacity.
SELECT *
FROM HOSPITALS
WHERE 
BED_CAPACITY > (SELECT AVG(BED_CAPACITY) FROM HOSPITALS)

-- 5. Get top 5 hospitals with the highest bed capacity.
SELECT HOSPITAL_NAME,
       BED_CAPACITY
       FROM HOSPITALS
       ORDER BY BED_CAPACITY DESC
       LIMIT 5

-- 6. Count male vs female patients.
SELECT GENDER,
       COUNT(*) AS TOTAL_PATIENTS
       FROM PATIENTS
       GROUP BY GENDER

-- 7. Find the youngest patient.
SELECT *
FROM PATIENTS
ORDER BY DATE_OF_BIRTH DESC
LIMIT 1

-- 8. Find oldest patient.
SELECT *
FROM PATIENTS
ORDER BY DATE_OF_BIRTH 
LIMIT 1

-- 9. List patients admitted in the last 30 days.
SELECT *
FROM PATIENTS
WHERE ADMISSION_DATE >= CURDATE() - INTERVAL 30 DAY

-- 10. Count patients by blood type.
SELECT BLOOD_TYPE, 
COUNT(*) AS TOTAL
FROM PATIENTS
GROUP BY BLOOD_TYPE

-- 11. Show total billing amount for each hospital.
SELECT  H.HOSPITAL_NAME,
        SUM(P.BILL) AS TOTAL_REVENUE
        FROM HOSPITALS AS H
        JOIN PATIENTS AS P ON H.HOSPITAL_ID = P.HOSPITAL_ID
        GROUP BY H.HOSPITAL_NAME

-- 12. Find hospitals that do not have any patients.
SELECT H.*
FROM HOSPITALS AS H
LEFT JOIN PATIENTS AS P 
ON
 H.HOSPITAL_ID = P.HOSPITAL_ID
WHERE P.PATIENT_ID IS NULL

-- 13. Count patients admitted per month.
SELECT DATE_FORMAT(ADMISSION_DATE, '%Y-%m') AS MONTH,
COUNT(*) AS TOTAL_ADMISSIONS
FROM PATIENTS
GROUP BY DATE_FORMAT(ADMISSION_DATE, '%Y-%m')

-- 14. Find total revenue per state.
SELECT H.STATE,
SUM(P.BILL) AS TOTAL_REVENUE
FROM HOSPITALS AS H
JOIN PATIENTS AS P ON H.HOSPITAL_ID = P.HOSPITAL_ID
GROUP BY H.STATE

-- 15. Find patients whose bill is above the overall average bill.
SELECT *
FROM PATIENTS
WHERE BILL > (SELECT AVG(BILL) FROM PATIENTS)

-- 16. Find the top 3 most common diagnoses.
SELECT DIAGNOSIS, 
COUNT(*) AS TOTAL
FROM PATIENTS
GROUP BY DIAGNOSIS
ORDER BY TOTAL DESC
LIMIT 3

-- 17. Find hospitals with more than 50 patients.
SELECT H.HOSPITAL_NAME,
COUNT(P.PATIENT_ID) AS TOTAL_PATIENTS
FROM HOSPITALS AS H
JOIN PATIENTS AS P ON H.HOSPITAL_ID = P.HOSPITAL_ID
GROUP BY H.HOSPITAL_NAME
HAVING COUNT(P.PATIENT_ID) > 50

-- 18. Find hospitals with no emergency services.
SELECT *
FROM HOSPITALS
WHERE EMERGENCY_SERVICES = 0

-- 19. List the 10 patients with the highest bill.
SELECT *
FROM PATIENTS
ORDER BY BILL DESC
LIMIT 10

-- 20. Find hospitals with average billing greater than 10,000.
SELECT H.HOSPITAL_NAME,
AVG(P.BILL) AS AVG_BILL
FROM HOSPITALS AS H
JOIN PATIENTS AS P ON H.HOSPITAL_ID = P.HOSPITAL_ID
GROUP BY H.HOSPITAL_NAME
HAVING AVG(P.BILL) > 10000

-- 21. Show patient count by hospital type.
SELECT H.HOSPITAL_TYPE, 
COUNT(P.PATIENT_ID) AS TOTAL_PATIENTS
FROM HOSPITALS AS H
LEFT JOIN PATIENTS AS P ON H.HOSPITAL_ID = P.HOSPITAL_ID
GROUP BY H.HOSPITAL_TYPE

-- 22. List patients with missing insurance information.
SELECT *
FROM PATIENTS
WHERE INSURANCE_PROVIDER IS NULL
OR INSURANCE_PROVIDER = ''

-- 23. Find states with more than 3 hospitals.
SELECT STATE,
COUNT(*) AS TOTAL_HOSPITALS
FROM HOSPITALS
GROUP BY STATE
HAVING COUNT(*) > 3

-- 24. Rank hospitals by total revenue.
SELECT H.HOSPITAL_NAME,
       SUM(P.BILL) AS TOTAL_REVENUE,
       RANK() OVER(ORDER BY SUM(P.BILL) DESC) AS RANKS
FROM HOSPITALS AS H
JOIN PATIENTS AS P ON H.HOSPITAL_ID = P.HOSPITAL_ID
GROUP BY H.HOSPITAL_NAME

-- 25. Rank patients by bill within each hospital.
SELECT *, 
RANK() OVER(PARTITION BY HOSPITAL_ID ORDER BY BILL DESC) AS BILL_RANK
FROM PATIENTS 

-- 26. Show patients admitted on weekends.
SELECT *
FROM PATIENTS
WHERE DAYOFWEEK(ADMISSION_DATE) IN (1,7)

-- 27. Find hospitals in cities with more than 1 hospital.
SELECT CITY,
COUNT(*) AS TOTAL
FROM HOSPITALS
GROUP BY CITY
HAVING COUNT(*) > 1

-- 28. Retrieve patients older than 60 years.
SELECT *
FROM PATIENTS
WHERE
TIMESTAMPDIFF(YEAR, DATE_OF_BIRTH, CURDATE()) > 60

-- 29. Show hospitals with at least one ICU-type diagnosis.
SELECT DISTINCT H.*
FROM HOSPITALS H
JOIN PATIENTS P ON H.HOSPITAL_ID = P.HOSPITAL_ID
WHERE P.DIAGNOSIS LIKE '%ICU%'

-- 30. Count patients by admission year.
SELECT YEAR(ADMISSION_DATE) AS ADMIT_YEAR,
COUNT(*) AS TOTAL
FROM PATIENTS
GROUP BY
YEAR(ADMISSION_DATE)

-- 31. Total patients by gender per hospital.
SELECT H.HOSPITAL_NAME,
P.GENDER, COUNT(*) AS TOTAL
FROM HOSPITALS AS H
JOIN PATIENTS AS P
ON
H.HOSPITAL_ID = P.HOSPITAL_ID
GROUP BY 
H.HOSPITAL_NAME, P.GENDER

-- 32. List hospitals starting with letter 'A'.
SELECT *
FROM HOSPITALS
WHERE
HOSPITAL_NAME LIKE "A%"

-- 33. Average bill by diagnosis.
SELECT DIAGNOSIS,
AVG(BILL) AS AVG_BILL
FROM PATIENTS
GROUP BY DIAGNOSIS

-- 34. Patients without room numbers.
SELECT *
FROM PATIENTS
WHERE ROOM_NUMBER IS NULL 
OR ROOM_NUMBER =" "

-- 35. Find the city with the highest bed capacity total.
SELECT CITY,
SUM(BED_CAPACITY) AS TOTAL_BEDS
FROM HOSPITALS
GROUP BY CITY
ORDER BY TOTAL_BEDS DESC
LIMIT 1

-- 36. Patients per age group (0–18, 19–40, 41–60, 60+).
SELECT 
CASE 
    WHEN TIMESTAMPDIFF(YEAR, DATE_OF_BIRTH, CURDATE()) <= 18 THEN "0-18"
     WHEN TIMESTAMPDIFF(YEAR, DATE_OF_BIRTH, CURDATE()) BETWEEN 19 AND 40 THEN "19-40"
     WHEN TIMESTAMPDIFF(YEAR, DATE_OF_BIRTH, CURDATE()) BETWEEN 41 AND 60 THEN "41-60"
  ELSE "60+"
END AS AGE_GROUP,
COUNT(*) AS TOTAL
FROM PATIENTS
GROUP BY AGE_GROUP

-- 37. Find hospitals whose name contains 'MEDICAL'.
SELECT *
FROM HOSPITALS
WHERE HOSPITAL_NAME LIKE "%MEDICAL%"

-- 38. Total number of insured vs non-insured patients.
SELECT 
CASE 
  WHEN INSURANCE_PROVIDER IS NULL OR INSURANCE_PROVIDER = " " THEN "NO INSURANCE"
  ELSE "INSURED"
END AS INSURANCE_STATUS,
COUNT(*) AS TOTAL
FROM PATIENTS
GROUP BY INSURANCE_STATUS

-- 39. Find the single highest bill in each state.
SELECT H.STATE,
MAX(P.BILL) AS MAX_BILL
FROM HOSPITALS AS H
JOIN PATIENTS AS P 
ON H.HOSPITAL_ID = P.HOSPITAL_ID
GROUP BY H.STATE

-- 40. Find states with no emergency hospitals.
SELECT STATE,
EMERGENCY_SERVICES
FROM HOSPITALS
WHERE 
EMERGENCY_SERVICES = 0 
OR EMERGENCY_SERVICES IS NULL

-- 41.Retrieve hospitals with more beds than the state average.
SELECT H.*
FROM HOSPITALS AS H
WHERE BED_CAPACITY >
( SELECT AVG(BED_CAPACITY)
FROM HOSPITALS AS H2
WHERE H2.STATE = H.STATE)

-- 42. Patients admitted in the same month as their birthday.
SELECT *
FROM PATIENTS
WHERE
MONTH(ADMISSION_DATE) = MONTH(DATE_OF_BIRTH)

-- 43. Find hospitals with the longest name.
SELECT *
FROM HOSPITALS
ORDER BY LENGTH(HOSPITAL_NAME) DESC
LIMIT 1

-- 44. Count diagnoses containing the word 'ACUTE'.
SELECT DIAGNOSIS,
COUNT(*) AS TOTAL_PATIENTS
FROM PATIENTS
WHERE DIAGNOSIS LIKE "%ACUTE%"
GROUP BY DIAGNOSIS

-- 45.find how many patients were admitted in each hospital per month
SELECT HOSPITAL_ID,
MONTH(ADMISSION_DATE) AS ADMISSION_MONTH,
COUNT(*) AS TOTAL_ADMISSIONS
FROM PATIENTS
GROUP BY HOSPITAL_ID,
         MONTH(ADMISSION_DATE)
ORDER BY HOSPITAL_ID,
          ADMISSION_MONTH


-- 46. Hospital with the highest average patient age.
SELECT H.HOSPITAL_NAME,
AVG(TIMESTAMPDIFF(YEAR, P.DATE_OF_BIRTH, CURDATE())) AS AVG_AGE
FROM HOSPITALS AS H
JOIN PATIENTS AS P 
ON H.HOSPITAL_ID = P.HOSPITAL_ID
GROUP BY H.HOSPITAL_NAME
ORDER BY AVG_AGE DESC
LIMIT 1

-- 47. Find diagnosis count per hospital.
SELECT H.HOSPITAL_NAME,
P.DIAGNOSIS,
COUNT(*) AS TOTAL
FROM HOSPITALS AS H
JOIN PATIENTS AS P
ON H.HOSPITAL_ID = P.HOSPITAL_ID
GROUP BY H.HOSPITAL_NAME, P.DIAGNOSIS

-- 48. Hospitals having more emergency patients than non-emergency patients.
SELECT H.HOSPITAL_NAME
FROM HOSPITALS AS H
JOIN PATIENTS AS P
ON H.HOSPITAL_ID = P.HOSPITAL_ID
GROUP BY H.HOSPITAL_NAME
HAVING SUM(P.DIAGNOSIS LIKE "%ER%") >
       SUM(P.DIAGNOSIS NOT LIKE "%ER%");

-- 49. Find patients who share same last name.
SELECT LAST_NAME, 
COUNT(*) AS TOTAL
FROM PATIENTS
GROUP BY LAST_NAME
HAVING COUNT(*) > 1

-- 50. Find patients admitted exactly 100 days ago.
SELECT *
FROM PATIENTS
WHERE 
ADMISSION_DATE = CURDATE() - INTERVAL 100 DAY

-- 51.FIND THE TOP 3 HOSPITALS WITH THE HIGHEST TOTAL BILL AMOUNT COLLECTED.
SELECT H.HOSPITAL_NAME,
       SUM(P.BILL) AS TOTAL_REVENUE
FROM HOSPITALS AS H
JOIN PATIENTS AS P
ON H.HOSPITAL_ID = P.HOSPITAL_ID
GROUP BY H.HOSPITAL_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 3 

-- 52.LIST HOSPITALS WHERE MORE THAN 40% OF THEIR PATIENTS ARE ADMITTED TO EMERGENCY SERVICES.
SELECT H.HOSPITAL_NAME
FROM HOSPITALS AS H
JOIN PATIENTS AS P
ON H.HOSPITAL_ID = P.HOSPITAL_ID
WHERE H.EMERGENCY_SERVICES = 1
GROUP BY H.HOSPITAL_NAME
HAVING COUNT(P.PATIENT_ID) > 
          (SELECT COUNT(*) * 0.40 FROM PATIENTS)

-- 53.FIND THE AVERAGE BILL PER GENDER WITHIN EACH HOSPITAL.
SELECT H.HOSPITAL_NAME,
       P.GENDER,
       AVG(P.BILL) AS AVG_BILL
FROM HOSPITALS AS H
JOIN PATIENTS AS P 
ON H.HOSPITAL_ID = P.HOSPITAL_ID
GROUP BY
       H.HOSPITAL_NAME, P.GENDER

-- 54.GET THE HOSPITAL WITH THE HIGHEST BED UTILIZATION (PATIENT COUNT / BED CAPACITY).
SELECT H.HOSPITAL_NAME,
       (COUNT(P.PATIENT_ID) / H.BED_CAPACITY)* 100 AS UTILIZATION_RATE
FROM HOSPITALS AS H
JOIN PATIENTS AS P 
ON H.HOSPITAL_ID = P.HOSPITAL_ID
GROUP BY H.HOSPITAL_NAME,
         H.BED_CAPACITY
ORDER BY UTILIZATION_RATE DESC

-- 55.FIND PATIENTS WHOSE BILL IS ABOVE THE AVERAGE BILL OF THEIR HOSPITAL.
SELECT P.*
FROM PATIENTS AS P
JOIN (SELECT HOSPITAL_ID,
              AVG(BILL) AS AVG_BILL
       FROM PATIENTS
       GROUP BY HOSPITAL_ID) AS A
ON P.HOSPITAL_ID = A.HOSPITAL_ID
WHERE P.BILL > A.AVG_BILL

-- 56.LIST HOSPITALS WHERE NO PATIENT HAS BLOOD TYPE ‘O+’.
SELECT H.HOSPITAL_NAME
FROM HOSPITALS AS H
WHERE 
H.HOSPITAL_ID NOT IN (
	SELECT DISTINCT HOSPITAL_ID
    FROM PATIENTS
    WHERE BLOOD_TYPE = "O+")

-- 57.FIND THE MOST COMMON DIAGNOSIS IN EACH HOSPITAL.
SELECT H.HOSPITAL_NAME,
       P.DIAGNOSIS,
       COUNT(*) AS TOTAL_CASES
FROM HOSPITALS AS H
JOIN PATIENTS AS P 
ON H.HOSPITAL_ID = P.HOSPITAL_ID
GROUP BY H.HOSPITAL_NAME, P.DIAGNOSIS
ORDER BY TOTAL_CASES DESC


-- 58.GET PATIENTS WHO ARE SHARING THE SAME ROOM (MORE THAN 1 PATIENT IN A ROOM).
SELECT ROOM_NUMBER,
COUNT(*) AS TOTAL_PATIENTS
FROM PATIENTS
GROUP BY ROOM_NUMBER
HAVING COUNT(*) > 1

-- 59.SHOW THE OLDEST PATIENT AND THE HOSPITAL THEY ARE ADMITTED TO.
SELECT FIRST_NAME,
       LAST_NAME,
       HOSPITAL_NAME,
       DATE_OF_BIRTH
FROM PATIENTS AS P
JOIN HOSPITALS AS H 
ON P.HOSPITAL_ID = H.HOSPITAL_ID
ORDER BY 4 
LIMIT 1

-- 60.CALCULATE YEARLY REVENUE PER STATE AND RANK STATES BY REVENUE.
SELECT STATE,
       SUM(P.BILL) AS TOTAL_REVENUE,
       RANK() OVER (ORDER BY SUM(P.BILL) DESC) AS STATE_RANK
FROM HOSPITALS AS H
JOIN PATIENTS AS P 
ON H.HOSPITAL_ID = P.HOSPITAL_ID
GROUP BY STATE



