-- Hospital and Patient Database SQL Script
-- Generated: 2025-11-13
-- Tables: hospitals, patients

-- Create hospitals table
CREATE TABLE hospitals (
    hospital_id INTEGER PRIMARY KEY,
    hospital_name VARCHAR(255) NOT NULL,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(2) NOT NULL,
    bed_capacity INTEGER NOT NULL,
    hospital_type VARCHAR(50) NOT NULL,
    emergency_services BOOLEAN NOT NULL
);

-- Create patients table
CREATE TABLE patients (
    patient_id INTEGER PRIMARY KEY,
    hospital_id INTEGER NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    date_of_birth DATE NOT NULL,
    gender VARCHAR(20) NOT NULL,
    blood_type VARCHAR(5) NOT NULL,
    admission_date DATE NOT NULL,
    diagnosis VARCHAR(500) NOT NULL,
    room_number VARCHAR(20) NOT NULL,
    insurance_provider VARCHAR(255) NOT NULL,
    FOREIGN KEY (hospital_id) REFERENCES hospitals(hospital_id)
);

-- Create indexes for better query performance
CREATE INDEX idx_patients_hospital_id ON patients(hospital_id);
CREATE INDEX idx_patients_admission_date ON patients(admission_date);
CREATE INDEX idx_patients_blood_type ON patients(blood_type);

-- Insert hospital data
INSERT INTO hospitals (hospital_id, hospital_name, city, state, bed_capacity, hospital_type, emergency_services) VALUES (1, 'Brighton General Hospital', 'Brighton', 'CA', 320, 'General', TRUE);
INSERT INTO hospitals (hospital_id, hospital_name, city, state, bed_capacity, hospital_type, emergency_services) VALUES (2, 'Cedar Creek Medical Center', 'Cedar Creek', 'TX', 210, 'Community', FALSE);
INSERT INTO hospitals (hospital_id, hospital_name, city, state, bed_capacity, hospital_type, emergency_services) VALUES (3, 'Maple Ridge Specialized Center', 'Maple Ridge', 'WA', 90, 'Specialized', TRUE);
INSERT INTO hospitals (hospital_id, hospital_name, city, state, bed_capacity, hospital_type, emergency_services) VALUES (4, 'Riverside University Hospital', 'Riverside', 'IL', 680, 'Teaching', TRUE);
INSERT INTO hospitals (hospital_id, hospital_name, city, state, bed_capacity, hospital_type, emergency_services) VALUES (5, 'Azure Hills General Hospital', 'Azure Hills', 'AZ', 410, 'General', TRUE);

-- Insert patient data
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (1, 1, 'Liam', 'Archer', '1990-03-15', 'Male', 'O+', '2024-04-12', 'Pneumonia, community-acquired', '201A', 'Sunrise Health Plus');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (2, 1, 'Emma', 'Nguyen', '1985-07-22', 'Female', 'A+', '2024-05-03', 'Acute bronchitis', '305B', 'CedarCare Advantage');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (3, 1, 'Noah', 'Martin', '1978-11-02', 'Male', 'B-', '2024-06-18', 'Heart failure exacerbation', '412', 'NorthPoint Mutual');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (4, 1, 'Olivia', 'Lopez', '1995-02-09', 'Female', 'AB+', '2024-07-29', 'Diabetic ketoacidosis', '210', 'Sunrise Health Plus');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (5, 1, 'James', 'Kim', '1962-09-14', 'Male', 'O-', '2024-08-12', 'Hip fracture', '118', 'CareWell Insurance');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (6, 1, 'Ava', 'Singh', '2008-04-28', 'Female', 'A-', '2024-09-01', 'Appendicitis', '322', 'NorthPoint Mutual');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (7, 1, 'Lucas', 'Brown', '2010-12-19', 'Male', 'B+', '2024-10-15', 'Asthma exacerbation', '420', 'CedarCare Advantage');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (8, 1, 'Mia', 'Perez', '1988-06-05', 'Female', 'O+', '2024-11-02', 'Pleurisy', '507', 'Sunrise Health Plus');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (9, 1, 'Ethan', 'Clark', '1999-01-31', 'Male', 'AB-', '2024-12-20', 'Gastroenteritis', '102', 'CareWell Insurance');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (10, 1, 'Isabella', 'Davis', '1956-08-08', 'Female', 'A+', '2024-03-28', 'Pneumonia, elderly', '218', 'NorthPoint Mutual');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (11, 1, 'Benjamin', 'Walker', '1972-04-17', 'Male', 'O+', '2024-02-18', 'Acute renal failure', '315', 'CedarCare Advantage');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (12, 1, 'Charlotte', 'Allen', '2003-09-09', 'Female', 'B-', '2024-01-25', 'Fractured wrist', '133', 'Sunrise Health Plus');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (13, 1, 'Jack', 'Young', '1968-05-05', 'Male', 'AB+', '2024-05-30', 'Cholecystitis', '401', 'CareWell Insurance');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (14, 1, 'Grace', 'Hill', '1992-03-21', 'Female', 'O-', '2024-06-14', 'Sepsis suspected', '208', 'NorthPoint Mutual');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (15, 1, 'Henry', 'Adams', '1980-10-10', 'Male', 'A+', '2024-07-02', 'Dehydration', '115', 'CedarCare Advantage');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (16, 2, 'Mia', 'Sanders', '1988-04-12', 'Female', 'A+', '2024-03-15', 'Pneumonia', '312A', 'HealthGuard Plus');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (17, 2, 'Liam', 'Wright', '1995-11-02', 'Male', 'O+', '2024-05-20', 'Acute appendicitis', '215', 'BlueCross Medical');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (18, 2, 'Sophia', 'Kim', '1979-08-28', 'Female', 'AB-', '2024-01-07', 'Chronic obstructive pulmonary disease', '410', 'MediSure Advantage');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (19, 2, 'Noah', 'Garcia', '1982-02-14', 'Male', 'B+', '2024-06-03', 'Fractured tibia', '108', 'CareFirst Plus');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (20, 2, 'Emma', 'Lopez', '1990-09-09', 'Female', 'O-', '2024-02-28', 'Gallstones', '220', 'HealthGuard Plus');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (21, 3, 'Liam', 'Hughes', '1984-02-17', 'Male', 'O+', '2024-06-12', 'Pneumonia, community-acquired', '210A', 'HealWell Insurance');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (22, 3, 'Emma', 'Clark', '1992-11-03', 'Female', 'A+', '2024-03-27', 'Acute appendicitis', '312B', 'Sunrise Health');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (23, 3, 'Noah', 'Patel', '1978-08-21', 'Male', 'B+', '2024-09-14', 'Congestive heart failure', '411', 'CareTrust+');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (24, 3, 'Sophia', 'Nguyen', '2006-04-05', 'Female', 'AB-', '2024-12-02', 'Fractured radius - after fall', '508', 'PrimeCare');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (25, 3, 'James', 'Kim', '2010-09-29', 'Male', 'O-', '2024-08-19', 'Asthma exacerbation', '256', 'Alliance Health');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (26, 3, 'Ava', 'Martinez', '1989-01-12', 'Female', 'A-', '2024-05-03', 'Diabetic ketoacidosis', '320', 'CarePlus');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (27, 4, 'Liam', 'Andrews', '1987-03-12', 'Male', 'O+', '2024-05-21', 'Pneumonia, community-acquired', '312A', 'Mercury Health');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (28, 4, 'Emma', 'Lopez', '1994-11-05', 'Female', 'A-', '2024-07-08', 'Acute appendicitis', '210B', 'BlueCross');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (29, 4, 'Noah', 'Kim', '2008-02-19', 'Male', 'B+', '2024-09-14', 'Fractured left arm', '415C', 'AtlasCare');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (30, 4, 'Olivia', 'Singh', '1979-06-30', 'Female', 'AB+', '2024-02-03', 'Chronic obstructive pulmonary disease (COPD) exacerbation', '522', 'Mercury Health');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (31, 4, 'James', 'Carter', '1962-12-02', 'Male', 'O-', '2024-12-01', 'Congestive heart failure', '118', 'BlueCross');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (32, 4, 'Ava', 'Brown', '2001-04-17', 'Female', 'A+', '2024-03-19', 'Migraine with aura', '203D', 'AtlasCare');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (33, 4, 'Lucas', 'Patel', '2015-08-29', 'Male', 'O+', '2024-08-28', 'Acute otitis media', '306', 'Mercury Health');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (34, 4, 'Mia', 'Davis', '1999-01-22', 'Female', 'B-', '2024-10-10', 'Gallstones with biliary colic', '409', 'BlueCross');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (35, 4, 'Ethan', 'Nguyen', '1980-07-07', 'Male', 'AB-', '2024-06-15', 'Appendicitis post-rupture', '176', 'AtlasCare');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (36, 4, 'Sophia', 'Martinez', '2006-03-03', 'Female', 'AB+', '2024-04-02', 'Asthma exacerbation requiring admission', '260A', 'Mercury Health');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (37, 4, 'Benjamin', 'Ng', '1969-09-09', 'Male', 'A-', '2024-01-18', 'Diabetes mellitus with infection', '334', 'BlueCross');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (38, 4, 'Isabella', 'Clark', '2010-05-14', 'Female', 'O+', '2024-11-22', 'Broken femur after fall', '120', 'AtlasCare');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (39, 4, 'Michael', 'Rodriguez', '1984-10-02', 'Male', 'A+', '2024-09-02', 'Pneumonia, aspiration', '410', 'Mercury Health');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (40, 4, 'Charlotte', 'Lee', '1992-12-12', 'Female', 'B+', '2024-05-28', 'Kyphosis-related pain requiring hospitalization', '215', 'BlueCross');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (41, 4, 'Henry', 'White', '1988-02-25', 'Male', 'AB-', '2024-07-07', 'Sepsis secondary to urinary tract infection', '101', 'AtlasCare');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (42, 4, 'Amelia', 'Hernandez', '1975-08-08', 'Female', 'O-', '2024-02-28', 'Kidney stones', '308', 'Mercury Health');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (43, 4, 'Daniel', 'Lo', '1997-06-06', 'Male', 'A-', '2024-12-20', 'Acute pancreatitis', '219', 'BlueCross');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (44, 4, 'Grace', 'Kim', '2003-09-09', 'Female', 'O+', '2024-03-30', 'Postoperative recovery from laparoscopic cholecystectomy', '312B', 'AtlasCare');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (45, 4, 'Jack', 'Brown', '2012-01-01', 'Male', 'B+', '2024-08-03', 'Conjunctivitis with secondary infections', '403', 'Mercury Health');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (46, 4, 'Zoe', 'Wright', '1985-04-04', 'Female', 'AB-', '2024-06-28', 'Hypoglycemia due to insulin mismanagement', '144', 'BlueCross');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (47, 4, 'Elijah', 'Hill', '1990-11-11', 'Male', 'A+', '2024-10-31', 'Gastroenteritis with dehydration', '137', 'AtlasCare');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (48, 4, 'Victoria', 'Lopez', '2009-02-28', 'Female', 'O-', '2024-01-05', 'Bronchitis', '222', 'Mercury Health');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (49, 4, 'Samuel', 'Gonzalez', '2018-07-07', 'Male', 'AB+', '2024-09-09', 'Tonsillitis', '315', 'BlueCross');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (50, 4, 'Layla', 'Nguyen', '2016-05-05', 'Female', 'A-', '2024-12-12', 'Fever and dehydration', '317', 'AtlasCare');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (51, 4, 'Owen', 'Khan', '2000-10-10', 'Male', 'B-', '2024-04-22', 'Acute kidney injury', '325', 'Mercury Health');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (52, 4, 'Grace', 'Patel', '1995-03-03', 'Female', 'O+', '2024-11-03', 'Pneumothorax secondary to trauma', '128', 'BlueCross');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (53, 4, 'Aaron', 'Dixon', '1982-08-08', 'Male', 'AB-', '2024-01-22', 'Severe dehydration', '254', 'AtlasCare');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (54, 4, 'Chloe', 'Young', '1970-04-04', 'Female', 'A+', '2024-05-15', 'Electrolyte imbalance', '102', 'Mercury Health');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (55, 4, 'Daniela', 'Moreno', '1993-12-12', 'Female', 'B+', '2024-07-19', 'Severe gastritis', '214', 'BlueCross');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (56, 4, 'Ryan', 'Stevens', '1989-06-06', 'Male', 'O-', '2024-02-14', 'Heart attack', '108', 'AtlasCare');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (57, 4, 'Hannah', 'Kim', '2002-01-01', 'Female', 'AB+', '2024-08-29', 'Acute bronchitis', '309', 'Mercury Health');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (58, 4, 'Mason', 'Anderson', '2011-03-03', 'Male', 'A-', '2024-03-18', 'Chickenpox', '133', 'BlueCross');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (59, 4, 'Ella', 'Martin', '1998-09-09', 'Female', 'O+', '2024-12-01', 'Iron deficiency anemia', '207', 'AtlasCare');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (60, 4, 'Aiden', 'Gomez', '2013-10-10', 'Male', 'B+', '2024-06-06', 'Epistaxis with anemia', '144-2', 'Mercury Health');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (61, 4, 'Sofia', 'Ramos', '2007-07-07', 'Female', 'AB-', '2024-03-25', 'Cystitis', '148', 'BlueCross');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (62, 4, 'Caleb', 'Rivera', '1992-04-04', 'Male', 'A+', '2024-08-12', 'Lyme disease with joint involvement', '512', 'AtlasCare');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (63, 4, 'Grace', 'Kelley', '1986-05-05', 'Female', 'O-', '2024-09-09', 'Hepatitis A', '211', 'Mercury Health');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (64, 4, 'Jonathan', 'Cohen', '1978-02-02', 'Male', 'AB+', '2024-04-27', 'Hyperglycemia', '205', 'BlueCross');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (65, 4, 'Scarlett', 'Santos', '2019-12-12', 'Female', 'A-', '2024-01-09', 'Urinary tract infection', '321', 'AtlasCare');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (66, 4, 'Henry', 'Griffin', '1958-06-06', 'Male', 'B-', '2024-11-15', 'Pneumothorax', '102B', 'Mercury Health');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (67, 4, 'Natalie', 'Fox', '1991-08-08', 'Female', 'AB-', '2024-05-03', 'Gastritis', '226', 'BlueCross');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (68, 4, 'Ian', 'Watson', '2004-11-11', 'Male', 'O+', '2024-08-04', 'Conjunctival hemorrhage', '309B', 'AtlasCare');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (69, 4, 'Penelope', 'Perez', '1996-03-03', 'Female', 'A-', '2024-02-02', 'Bronchiolitis', '350', 'Mercury Health');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (70, 4, 'Jonah', 'Diaz', '2012-09-09', 'Male', 'B-', '2024-07-07', 'Strep throat', '201', 'BlueCross');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (71, 4, 'Layla', 'Kim', '1983-01-01', 'Female', 'AB+', '2024-10-10', 'Hyperthyroidism flare', '306A', 'AtlasCare');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (72, 4, 'Alexander', 'Baker', '1999-08-08', 'Male', 'O-', '2024-12-29', 'Severe dehydration from gastroenteritis', '133A', 'Mercury Health');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (73, 4, 'Aria', 'Ng', '2014-04-04', 'Female', 'A+', '2024-03-01', 'Ear infection', '112', 'BlueCross');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (74, 4, 'Mateo', 'Rojas', '2005-06-06', 'Male', 'B+', '2024-06-15', 'Croup', '114', 'AtlasCare');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (75, 4, 'Chloe', 'Silva', '1998-10-10', 'Female', 'O+', '2024-09-18', 'Chronic back pain requiring care', '409A', 'Mercury Health');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (76, 4, 'Wyatt', 'Young', '2010-02-02', 'Male', 'AB+', '2024-05-01', 'Flu with pneumonia', '318', 'BlueCross');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (77, 4, 'Ella', 'Rivera', '1987-07-07', 'Female', 'A-', '2024-08-25', 'Hyperglycemia with dehydration', '221', 'AtlasCare');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (78, 4, 'Carson', 'Flores', '2013-01-01', 'Male', 'B-', '2024-12-04', 'Skin infection', '332', 'Mercury Health');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (79, 4, 'Lila', 'Ortiz', '2002-08-08', 'Female', 'AB-', '2024-04-04', 'Kidney stones with infection', '327', 'BlueCross');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (80, 4, 'Calvin', 'Ng', '1993-11-11', 'Male', 'O-', '2024-09-15', 'Salmonella infection', '206', 'AtlasCare');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (81, 4, 'Sophie', 'Lee', '1990-05-05', 'Female', 'A+', '2024-01-25', 'Anemia due to iron deficiency', '230', 'Mercury Health');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (82, 4, 'Oliver', 'Ward', '1983-03-03', 'Male', 'B+', '2024-10-02', 'Stomach ulcer', '238', 'BlueCross');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (83, 4, 'Victoria', 'Parker', '1977-04-04', 'Female', 'O-', '2024-12-11', 'Heart failure exacerbation', '219B', 'AtlasCare');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (84, 4, 'Grayson', 'Kim', '2017-05-05', 'Male', 'AB+', '2024-06-20', 'Respiratory syncytial virus (RSV)', '309A', 'Mercury Health');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (85, 4, 'Hazel', 'Diaz', '2009-09-09', 'Female', 'A-', '2024-02-02', 'Allergic reaction with hives', '327A', 'BlueCross');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (86, 4, 'Daniel', 'Gonzales', '1996-12-12', 'Male', 'B+', '2024-03-15', 'Viral gastroenteritis', '241', 'AtlasCare');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (87, 4, 'Alice', 'Schmidt', '1985-08-08', 'Female', 'AB-', '2024-01-04', 'Hypotension', '120A', 'Mercury Health');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (88, 4, 'Jack', 'Novak', '1998-06-06', 'Male', 'O+', '2024-11-28', 'Liver function abnormality', '402', 'BlueCross');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (89, 4, 'Aria', 'Kaur', '1990-01-01', 'Female', 'A-', '2024-05-09', 'Gallbladder disease', '308A', 'AtlasCare');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (90, 4, 'Eli', 'Cooper', '2019-03-03', 'Male', 'B-', '2024-04-04', 'Common cold', '132', 'Mercury Health');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (91, 4, 'Natalie', 'Fisher', '2004-07-07', 'Female', 'AB+', '2024-03-25', 'Bronchospasm', '324', 'BlueCross');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (92, 4, 'Miles', 'Tan', '1991-04-04', 'Male', 'O+', '2024-12-01', 'Chronic kidney disease stage 3', '208', 'AtlasCare');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (93, 4, 'Ivy', 'Nguyen', '2013-02-02', 'Female', 'A+', '2024-08-08', 'Food poisoning', '109', 'Mercury Health');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (94, 4, 'Caleb', 'Kim', '2000-10-10', 'Male', 'B+', '2024-01-18', 'Sinusitis', '243', 'BlueCross');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (95, 4, 'Samantha', 'Brown', '1994-04-04', 'Female', 'O-', '2024-07-07', 'Hyperemesis gravidarum (pregnancy related)', '236', 'AtlasCare');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (96, 4, 'Jonah', 'Wong', '1987-05-05', 'Male', 'AB-', '2024-09-09', 'Renal colic', '215A', 'Mercury Health');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (97, 4, 'Grace', 'Allen', '1992-07-07', 'Female', 'A-', '2024-06-30', 'Viral meningitis', '281', 'BlueCross');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (98, 4, 'Omar', 'Rahman', '1989-01-01', 'Male', 'O+', '2024-02-20', 'Septicemia', '287', 'AtlasCare');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (99, 4, 'Zara', 'Ali', '2003-08-08', 'Female', 'AB+', '2024-12-31', 'Croup', '290', 'Mercury Health');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (100, 4, 'Wyatt', 'King', '2010-06-06', 'Male', 'A+', '2024-01-15', 'Iron deficiency anemia in children', '109A', 'BlueCross');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (101, 4, 'Luna', 'Pena', '1998-12-12', 'Female', 'B-', '2024-11-10', 'Migraine without aura', '315B', 'AtlasCare');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (102, 4, 'Aaron', 'Harper', '1986-03-03', 'Male', 'AB+', '2024-04-04', 'Gastric ulcer', '205A', 'Mercury Health');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (103, 4, 'Sophie', 'Stone', '2009-10-10', 'Female', 'O-', '2024-08-08', 'Strep pharyngitis', '340', 'BlueCross');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (104, 4, 'Jackson', 'Kim', '2011-01-01', 'Male', 'A-', '2024-05-05', 'Epilepsy monitoring', '351', 'AtlasCare');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (105, 4, 'Ava', 'Park', '2018-12-12', 'Female', 'AB-', '2024-09-24', 'Bronchopneumonia', '356', 'Mercury Health');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (106, 4, 'Leo', 'Chen', '2002-02-02', 'Male', 'O-', '2024-03-08', 'Viral gastroenteritis', '216', 'BlueCross');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (107, 4, 'Molly', 'Reed', '1989-09-09', 'Female', 'A+', '2024-12-24', 'Cholecystitis', '317A', 'AtlasCare');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (108, 4, 'Carter', 'Clark', '1993-04-04', 'Male', 'B+', '2024-04-14', 'Pleurisy', '420', 'Mercury Health');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (109, 4, 'Zoey', 'Ortiz', '2005-07-07', 'Female', 'A-', '2024-01-28', 'Dermatitis', '425', 'BlueCross');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (110, 4, 'Kai', 'Kim', '2013-08-08', 'Male', 'O+', '2024-11-21', 'Cochlear implant follow-up', '430', 'AtlasCare');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (111, 4, 'Nora', 'Ng', '2006-01-01', 'Female', 'AB-', '2024-02-22', 'Nephrolithiasis (kidney stones)', '431', 'Mercury Health');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (112, 4, 'Evelyn', 'Garcia', '1999-05-05', 'Female', 'A-', '2024-10-28', 'Severe hypertension with chest pain', '432', 'BlueCross');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (113, 4, 'Owen', 'Hughes', '1992-12-12', 'Male', 'B-', '2024-06-26', ' cellulitis of leg', '433', 'AtlasCare');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (114, 4, 'Ari', 'Khan', '2010-03-03', 'Male', 'AB+', '2024-05-29', 'Asthma', '434', 'Mercury Health');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (115, 4, 'Sienna', 'Diaz', '2019-07-07', 'Female', 'A+', '2024-08-08', 'Urinary tract infection', '435', 'BlueCross');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (116, 4, 'Henry', 'Perez', '1988-04-04', 'Male', 'O-', '2024-09-18', 'Gastritis', '436', 'AtlasCare');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (117, 4, 'Mila', 'Riley', '2009-06-06', 'Female', 'B+', '2024-12-05', 'Stomach flu', '437', 'Mercury Health');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (118, 4, 'Caden', 'Norris', '2014-08-08', 'Male', 'A+', '2024-02-15', 'Bronchitis', '438', 'BlueCross');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (119, 4, 'Grace', 'Williamson', '1995-05-05', 'Female', 'O+', '2024-11-07', 'Urinary retention', '439', 'AtlasCare');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (120, 4, 'Jonah', 'Ferguson', '1981-10-10', 'Male', 'B-', '2024-03-10', 'Gastroenteritis', '440', 'Mercury Health');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (121, 4, 'Chloe', 'Fox', '2002-09-09', 'Female', 'AB+', '2024-12-22', 'Anemia of chronic disease', '441', 'BlueCross');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (122, 4, 'Ethan', 'Guzman', '1990-02-02', 'Male', 'A-', '2024-04-04', 'Pancreatitis', '442', 'AtlasCare');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (123, 4, 'Kai', 'Ortiz', '2011-06-06', 'Male', 'O+', '2024-01-19', 'Conjunctivitis', '443', 'Mercury Health');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (124, 4, 'Stella', 'Santos', '2016-04-04', 'Female', 'A+', '2024-07-29', 'Ear canal infection', '444', 'BlueCross');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (125, 4, 'Isaac', 'Kim', '2013-12-12', 'Male', 'B+', '2024-05-07', 'Skin rash', '445', 'AtlasCare');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (126, 4, 'Jade', 'Lee', '1992-02-02', 'Female', 'AB-', '2024-09-01', 'Thyroid nodules', '446', 'Mercury Health');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (127, 5, 'Mia', 'Chen', '1987-03-14', 'Female', 'A+', '2024-02-10', 'Pneumonia', '305A', 'SummitCare');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (128, 5, 'Liam', 'Patel', '1992-11-22', 'Male', 'O+', '2024-03-18', 'Fractured radius', '210B', 'National Mutual');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (129, 5, 'Emma', 'Garcia', '1978-07-04', 'Female', 'AB-', '2024-01-29', 'Acute appendicitis', '412', 'CareFirst Plus');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (130, 5, 'Noah', 'Kim', '2005-09-17', 'Male', 'B+', '2024-04-05', 'Asthma exacerbation', '118', 'Allied Health');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (131, 5, 'Sophia', 'Nguyen', '1999-02-28', 'Female', 'O-', '2024-05-12', 'Cholelithiasis', '220C', 'PrimeGuard');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (132, 5, 'James', 'Brown', '1966-12-03', 'Male', 'A-', '2024-06-03', 'Heart failure', '305B', 'UnityCare');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (133, 5, 'Olivia', 'Singh', '1984-04-19', 'Female', 'AB+', '2024-02-24', 'Gallbladder infection', '308', 'SecureHealth');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (134, 5, 'Ethan', 'Park', '1995-08-08', 'Male', 'A+', '2024-03-30', 'Pediatric appendicitis (adult)', '315', 'MediTrust');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (135, 5, 'Ava', 'Lopez', '2002-05-15', 'Female', 'B-', '2024-04-18', 'Migraine with aura', '402', 'BrightPath');
INSERT INTO patients (patient_id, hospital_id, first_name, last_name, date_of_birth, gender, blood_type, admission_date, diagnosis, room_number, insurance_provider) VALUES (136, 5, 'Lucas', 'Silva', '1972-01-21', 'Male', 'O+', '2024-01-15', 'Chronic kidney disease - flare', '501', 'CareSure');

